version: '3.8'

services:

  mysql_oauth_server_client:
    image: mysql:latest
    container_name: mysql_oauth_server_client
    environment:
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3307:3306"
    volumes:
      - mysql_data_server:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

  oauth_client:
    container_name: node_client
    build:
      context: ./client
    ports:
      - "3000:3000"
      - "9229:9229"
    command: node --inspect=0.0.0.0:9229 --nolazy app.js
    volumes:
      - ./client:/app
    depends_on:
      - mysql_oauth_server_client
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: social

  oauth_server:
    container_name: node_server
    build:
      context: ./server
    ports:
      - "5000:5000"
      - "9230:9229"
    command: node --inspect=0.0.0.0:9229 --nolazy app.js
    volumes:
      - ./server:/app
    depends_on:
      - mysql_oauth_server_client
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: oauth

volumes:
  mysql_data_server:
  mysql_data_client:


