version: '3.8'

services:

  mysql_oauth_server:
    image: mysql:latest
    container_name: mysql_oauth_server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oauth

    ports: 
      - "3307:3306"
    volumes:
      - mysql_data_server:/var/lib/mysql
      - ./server/oauth.sql:/docker-entrypoint-initdb.d/oauth.sql

  
  mysql_oauth_client:
    image: mysql:latest
    container_name: mysql_oauth_client
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social

    ports:
      - "3308:3306"
    volumes:
      - mysql_data_client:/var/lib/mysql
      - ./client/social.sql:/docker-entrypoint-initdb.d/social.sql

  
  oauth_client:
    container_name: node_client
    build: 
      context: ./client
    ports:
      - "3000:3000"
      - "9229:9229"
    command: node --inspect=0.0.0.0:9229 app.js
    volumes:
      - ./client:/app
    depends_on:
      - mysql_oauth_client
    environment:
      DB_HOST: mysql_oauth_client
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: social

  oauth_server:
    container_name: node_server
    build: 
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - mysql_oauth_server
    environment:
      DB_HOST: mysql_oauth_server
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: oauth

volumes:
  mysql_data_server:
  mysql_data_client:


    